ENV['RCT_NEW_ARCH_ENABLED'] = '1'

ws_dir = Pathname.new(__dir__)
ws_dir = ws_dir.parent until
  File.exist?("#{ws_dir}/node_modules/react-native-test-app/test_app.rb") ||
  ws_dir.expand_path.to_s == '/'
require "#{ws_dir}/node_modules/react-native-test-app/test_app.rb"

workspace 'FprotExample.xcworkspace'

use_test_app! :hermes_enabled => true, :fabric_enabled => true, :use_new_arch => true,
  :post_install => proc { |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 15.1
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        end
      end
    end
    # RN Test App regenerates Info.plist. Apply this on every pod installation.
    installer.aggregate_targets.map(&:user_project).compact.uniq.each do |project|
      plist = File.join(File.dirname(project.path.to_s), 'Info.plist')
      next unless File.exist?(plist)
      info = Xcodeproj::Plist.read_from_path(plist)
      info['NSLocalNetworkUsageDescription'] = 'Connect to your friend and the signaling server for encrypted peer-to-peer chat.'
      Xcodeproj::Plist.write_to_path(info, plist)
    end
  }
